package acclient

import (
	"github.com/subiz/header"
)

func ListDefaultDefs() []*header.AttributeDefinition {
	return []*header.AttributeDefinition{
		&header.AttributeDefinition{
			Name:     "Google Analytics Client ID",
			Label:    "Google Analytics Client ID",
			Key:      "ga_client_id",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:       "First Paid Order",
			Label:      "First Paid Order",
			Key:        "first_paid_order_id",
			Type:       "text",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:       "Banned",
			Label:      "Banned",
			I18NLabel:   &header.I18NString{Vi_VN: "Bị chặn", En_US: "Banned"},
			Key:        "is_ban",
			Type:       "boolean",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:        "Avatar",
			Label:       "Ảnh đại diện",
			Description: "Ảnh cá nhân của người dùng",
			I18NLabel:   &header.I18NString{Vi_VN: "Ảnh đại diện", En_US: "Avatar"},
			Key:         "avatar_url",
			Type:        "text",
			IsImage:     true,
			IsSystem:    true,
		},
		&header.AttributeDefinition{
			Name:        "Đã theo dõi",
			Label:       "Đã theo dõi",
			Description: "Người dùng đã theo dõi Zalo OA hoặc Instagram",
			I18NLabel:   &header.I18NString{Vi_VN: "Đã theo dõi", En_US: "Is Followed"},
			Key:         "is_followed",
			Type:        "boolean",
			IsSystem:    true,
			IsReadonly:  true,
		},
		&header.AttributeDefinition{
			Name:        "Ẩn danh",
			Label:       "Ẩn danh",
			Description: "Người dùng ẩn danh trên Zalo",
			I18NLabel:   &header.I18NString{Vi_VN: "Ẩn danh", En_US: "Anonymous"},
			Key:         "is_anonymous",
			Type:        "boolean",
			IsSystem:    true,
			IsReadonly:  true,
		},
		&header.AttributeDefinition{
			Name:      "Email",
			Label:     "Email",
			I18NLabel: &header.I18NString{Vi_VN: "Email", En_US: "Email"},
			Key:       "emails",
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:     "Rank",
			Label:    "Rank",
			Key:      "rank",
			Type:     "number",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:     "External ID",
			Label:    "External ID",
			Key:      "external_id",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:      "Facebook",
			Label:     "Facebook",
			Key:       "facebook",
			I18NLabel: &header.I18NString{Vi_VN: "Facebook cá nhân", En_US: "Personal facebook page"},
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:      "Zalo",
			Label:     "Zalo",
			Key:       "zalo",
			I18NLabel: &header.I18NString{Vi_VN: "Zalo cá nhân", En_US: "Personal zalo page"},
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:      "Job title",
			Label:     "Job title",
			Key:       "job_title",
			I18NLabel: &header.I18NString{Vi_VN: "Chức danh", En_US: "Job title"},
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:      "Owner",
			Label:     "Lead owner",
			Key:       "owner",
			I18NLabel: &header.I18NString{Vi_VN: "Phụ trách", En_US: "Lead owner"},
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:       "Thời điểm phân lead",
			Label:      "Thời điểm phân lead",
			Key:        "lead_assigned_at",
			I18NLabel:  &header.I18NString{Vi_VN: "Thời điểm phân lead", En_US: "Lead assigned at"},
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:      "Status",
			Label:     "Status",
			I18NLabel: &header.I18NString{Vi_VN: "Trạng thái", En_US: "Status"},
			Key:       "status",
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:        "Fullname",
			Label:       "Họ tên",
			Description: "Họ tên đầy đủ của người dùng",
			I18NLabel:   &header.I18NString{Vi_VN: "Họ tên", En_US: "Fullname"},
			Key:         "fullname",
			Type:        "text",
			IsSystem:    true,
		},
		&header.AttributeDefinition{
			Name:      "Address",
			Label:     "Address",
			I18NLabel: &header.I18NString{Vi_VN: "Địa chỉ", En_US: "Address"},
			Key:       "address",
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:     "City",
			Label:    "City",
			Key:      "city",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:     "District",
			Label:    "District",
			Key:      "district",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:      "Phone",
			Label:     "Phone",
			I18NLabel: &header.I18NString{Vi_VN: "SĐT", En_US: "Phone"},
			Key:       "phones",
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:     "Focused",
			Label:    "Focused",
			Key:      "focused",
			Type:     "boolean",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:      "Gender",
			Label:     "Gender",
			I18NLabel: &header.I18NString{Vi_VN: "Giới tính", En_US: "Gender"},
			Key:       "gender",
			Type:      "text",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:       "Created",
			Label:      "Created",
			Key:        "created",
			I18NLabel:  &header.I18NString{Vi_VN: "Tạo lúc", En_US: "Creation time"},
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:       "Modified",
			Label:      "Modified",
			I18NLabel:  &header.I18NString{Vi_VN: "Cập nhật lúc", En_US: "Modified at"},
			Key:        "modified",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:       "Seen",
			Label:      "Hoạt động cuối",
			I18NLabel:  &header.I18NString{Vi_VN: "Hoạt động cuối", En_US: "Last seen"},
			Key:        "seen",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:       "Total conversations",
			Label:      "Total conversations",
			Key:        "total_conversations",
			Type:       "number",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:     "City name",
			Label:    "City name",
			Key:      "trace_city_name",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:     "Country code",
			Label:    "Country code",
			Key:      "trace_country_code",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:     "Country name",
			Label:    "Country name",
			Key:      "trace_country_name",
			Type:     "text",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Name:  "Last message sent time",
			Label: "Last message sent time",
			I18NLabel: &header.I18NString{
				Vi_VN: "Thời điểm nhắn tin gần nhất",
				En_US: "Last message sent time",
			},
			Key:        "last_message_sent",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:  "Last order created at",
			Label: "Last Order Created At",
			I18NLabel: &header.I18NString{
				Vi_VN: "Thời điểm đơn tạo gần nhất",
				En_US: "Last order created at",
			},
			Key:        "last_order_at",
			Type:       "datetime",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:  "First channel touchpoint",
			Label: "First channel touchpoint",
			I18NLabel: &header.I18NString{
				Vi_VN: "Nơi tạo khách hàng",
				En_US: "First channel touchpoint",
			},
			Key:        "first_channel_touchpoint",
			Type:       "text",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:       "First session source referer",
			Label:      "First session source referer",
			Key:        "first_session_referer",
			Type:       "text",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Name:        "First tracking link",
			Label:       "First tracking link",
			Key:         "first_session_tracking_link",
			Description: "The link that user click from referer site to go to our site",
			Type:        "text",
			IsSystem:    true,
			IsReadonly:  true,
		},

		&header.AttributeDefinition{
			Label: "Thời gian tạo lead",
			I18NLabel: &header.I18NString{
				Vi_VN: "Thời gian tạo lead",
				En_US: "Convert to lead at",
			},
			Type:       "datetime",
			Key:        "lead_at",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Label: "Loại nguồn lead",
			I18NLabel: &header.I18NString{
				Vi_VN: "Loại nguồn lead",
				En_US: "Lead source type",
			},
			Type:     "text",
			Key:      "lead_source",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			// alway move forward
			Label:     "Giai đoạn vòng đời",
			I18NLabel: &header.I18NString{Vi_VN: "Giai đoạn vòng đời", En_US: "Lifecycle stage"},
			Type:      "text",
			Select:    "dropdown",
			Items: []*header.AttributeDefinitionListItem{
				{Value: "subscribe", I18NLabel: &header.I18NString{En_US: "Subscriber", Vi_VN: "Đã theo dõi"}, Label: "Đã theo dõi"},
				{Value: "trial", I18NLabel: &header.I18NString{En_US: "Trial", Vi_VN: "Dùng thử"}, Label: "Dùng thử"},
				{Value: "lead", I18NLabel: &header.I18NString{En_US: "Lead", Vi_VN: "Quan tâm"}, Label: "Quan tâm"},
				{Value: "marketing qualified lead", I18NLabel: &header.I18NString{En_US: "Marketing Qualified Lead", Vi_VN: "Tiềm năng chuẩn Marketing"}, Label: "Tiềm năng chuẩn Marketing"},
				{Value: "sale qualified lead", I18NLabel: &header.I18NString{En_US: "Sale Qualified Lead", Vi_VN: "Tiềm năng chuẩn Sale"}, Label: "Tiềm năng chuẩn Sale"},
				{Value: "opportunity", I18NLabel: &header.I18NString{En_US: "Opportunity", Vi_VN: "Rất tiềm năng"}, Label: "Rất tiềm năng"},
				{Value: "customer", I18NLabel: &header.I18NString{En_US: "Customer", Vi_VN: "Khách hàng"}, Label: "Khách hàng"},
			},
			Key:      "lifecycle_stage",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Label:      "Thời điểm chuyển giai đoạn",
			I18NLabel:  &header.I18NString{Vi_VN: "Thời điểm chuyển giai đoạn", En_US: "Lifecycle stage start at"},
			Type:       "datetime",
			Key:        "lifecycle_stage_start_at",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Label:     "Trạng thái lead",
			I18NLabel: &header.I18NString{Vi_VN: "Trạng thái lead", En_US: "Lead status"},
			Type:      "text",
			Select:    "dropdown",
			Items: []*header.AttributeDefinitionListItem{
				{Value: "new", I18NLabel: &header.I18NString{En_US: "New", Vi_VN: "Mới"}, Label: "Mới"},
				{Value: "open", I18NLabel: &header.I18NString{En_US: "Open", Vi_VN: "Mở"}, Label: "Mở"},
				{Value: "in progress", I18NLabel: &header.I18NString{En_US: "In Progress", Vi_VN: "Đang xử lý"}, Label: "Đang xử lý"},
				{Value: "open deal", I18NLabel: &header.I18NString{En_US: "Open deal", Vi_VN: "Đã mở deal"}, Label: "Đã mở deal"},
				{Value: "unqualified", I18NLabel: &header.I18NString{En_US: "Unqualified", Vi_VN: "Không đạt"}, Label: "Không đạt"},
				{Value: "attempted to contact", I18NLabel: &header.I18NString{En_US: "Attempted To Connect", Vi_VN: "Đã cố liên lạc"}, Label: "Đã cố liên lạc"},
				{Value: "connected", I18NLabel: &header.I18NString{En_US: "Connected", Vi_VN: "Đã kết nối"}, Label: "Đã kết nối"},
				{Value: "bad timming", I18NLabel: &header.I18NString{En_US: "Bad timming", Vi_VN: "Sai thời điểm"}, Label: "Sai thời điểm"},
			},
			Key:      "lead_status",
			IsSystem: true,
		},
		&header.AttributeDefinition{
			Label:     "Nguồn lead",
			I18NLabel: &header.I18NString{Vi_VN: "Nguồn lead", En_US: "Lead source"},
			Type:      "text",
			Key:       "lead_source",
			IsSystem:  true,
		},
		&header.AttributeDefinition{
			Name:       "Tổng số đơn",
			Label:      "Tổng số đơn",
			I18NLabel:  &header.I18NString{Vi_VN: "Tổng số đơn", En_US: "Number of orders"},
			Key:        "num_orders",
			Type:       "number",
			IsSystem:   true,
			IsReadonly: true,
		},
		&header.AttributeDefinition{
			Label:       "Tổng giá trị đơn",
			Description: "Tổng giá trị các đơn đã xác nhận",
			I18NLabel:   &header.I18NString{Vi_VN: "Tổng giá trị đơn", En_US: "Total order value"},
			Type:        "number",
			Key:         "total_order_value",
			IsSystem:    true,
		},
		&header.AttributeDefinition{
			Name:       "First Interact",
			Label:      "First Interact",
			Key:        "first_interact",
			IsSystem:   true,
			IsReadonly: true,
		},
	}
}
